# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ntest.proto\x12\x05proto\"\xce\x02\n\x06VMInfo\x12\n\n\x02Id\x18\x01 \x01(\t\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x0e\n\x06Status\x18\x03 \x01(\t\x12\x11\n\tPublicIps\x18\x04 \x03(\t\x12\x12\n\nPrivateIps\x18\x05 \x03(\t\x12#\n\x06\x43onfig\x18\x06 \x01(\x0b\x32\x13.proto.VMInfoConfig\x12\x0c\n\x04Host\x18\x07 \x01(\t\x12\n\n\x02Sn\x18\x08 \x01(\t\x12\x10\n\x08Provider\x18\t \x01(\t\x12\x14\n\x0c\x43reateUserId\x18\n \x01(\t\x12\x12\n\nCreateTime\x18\x0b \x01(\t\x12\x12\n\nIsTemplate\x18\x0c \x01(\t\x12\x12\n\nVmPathName\x18\r \x01(\t\x12\x0c\n\x04\x44\x65sc\x18\x0e \x01(\t\x12\x1a\n\x12NetworkInterfaceID\x18\x0f \x03(\t\x12\x14\n\x0cPortGroupsId\x18\x10 \x03(\t\x12\x10\n\x08VolumeId\x18\x11 \x03(\t\"+\n\x0cVMInfoConfig\x12\x0e\n\x06Memory\x18\x01 \x01(\x05\x12\x0b\n\x03\x43pu\x18\x02 \x01(\x05\x62\x06proto3')
)




_VMINFO = _descriptor.Descriptor(
  name='VMInfo',
  full_name='proto.VMInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='proto.VMInfo.Id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Name', full_name='proto.VMInfo.Name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Status', full_name='proto.VMInfo.Status', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PublicIps', full_name='proto.VMInfo.PublicIps', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PrivateIps', full_name='proto.VMInfo.PrivateIps', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Config', full_name='proto.VMInfo.Config', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Host', full_name='proto.VMInfo.Host', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Sn', full_name='proto.VMInfo.Sn', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Provider', full_name='proto.VMInfo.Provider', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CreateUserId', full_name='proto.VMInfo.CreateUserId', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CreateTime', full_name='proto.VMInfo.CreateTime', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IsTemplate', full_name='proto.VMInfo.IsTemplate', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='VmPathName', full_name='proto.VMInfo.VmPathName', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Desc', full_name='proto.VMInfo.Desc', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NetworkInterfaceID', full_name='proto.VMInfo.NetworkInterfaceID', index=14,
      number=15, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PortGroupsId', full_name='proto.VMInfo.PortGroupsId', index=15,
      number=16, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='VolumeId', full_name='proto.VMInfo.VolumeId', index=16,
      number=17, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=356,
)


_VMINFOCONFIG = _descriptor.Descriptor(
  name='VMInfoConfig',
  full_name='proto.VMInfoConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Memory', full_name='proto.VMInfoConfig.Memory', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Cpu', full_name='proto.VMInfoConfig.Cpu', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=401,
)

_VMINFO.fields_by_name['Config'].message_type = _VMINFOCONFIG
DESCRIPTOR.message_types_by_name['VMInfo'] = _VMINFO
DESCRIPTOR.message_types_by_name['VMInfoConfig'] = _VMINFOCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VMInfo = _reflection.GeneratedProtocolMessageType('VMInfo', (_message.Message,), dict(
  DESCRIPTOR = _VMINFO,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:proto.VMInfo)
  ))
_sym_db.RegisterMessage(VMInfo)

VMInfoConfig = _reflection.GeneratedProtocolMessageType('VMInfoConfig', (_message.Message,), dict(
  DESCRIPTOR = _VMINFOCONFIG,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:proto.VMInfoConfig)
  ))
_sym_db.RegisterMessage(VMInfoConfig)


# @@protoc_insertion_point(module_scope)
